cocinitas/Cocinitas/Controllers/recetasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cocinitas.Models;
using Microsoft.AspNetCore.Http;

namespace Cocinitas.Controllers
{
    public class recetasController : Controller
    {
        private readonly CocinitasContext _context;

        int vegeta = 0;
        int vegan = 0;
        int celia = 0;
        int lacte = 0;

        public recetasController(CocinitasContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> subereceta(string nombre, string vegetariano, 
        string vegano, string celiaco, string lacteos, string tiempo, int orden, 
        string calorias, string ingrediente1, string ingrediente2, string ingrediente3, 
        string ingrediente4, string ingredientestexto, string recetatexto)  
        {

            ViewData["usNombre"] = HttpContext.Session.GetString("usNombre");
            
            if (nombre == null || tiempo == null || calorias == null)
            {

                ViewData["errores"] = "Rellene los campos con *";
                return View();
            }
            else
            {
                


                compruebacheckbox(vegetariano, vegano, celiaco, lacteos);




                recetas receta = new recetas(nombre, vegeta, vegan, celia, lacte, tiempo, orden, calorias, ingrediente1, ingrediente2, ingrediente3, ingrediente4, ingredientestexto, recetatexto);

                //obtengo la id del usuario de la sesion actual
                
                receta.IDus = int.Parse(HttpContext.Session.GetInt32("usID").ToString());



                string error = receta.verificar();

                if (error.Equals(""))
                {
                    receta.subereceta();
                    receta.ingplato();
                }
                else
                {
                    //error de formulario
                    receta.problema = 3;

                }

                switch (receta.problema)
                {
                    case 1:
                        ViewData["errores"] = "tabla platos no recibe";
                        break;
                    case 2:
                        ViewData["errores"] = "tabla ingplatos no recibe";
                        break;
                    case 3:
                        ViewData["errores"] = error;
                        break;

                }

                ViewData["idplato"] = receta.ID;
                return View();
            }

            //return View();
            
            
        }

        public void compruebacheckbox(string vegetariano, string vegano, string celiaco, string lacteos)
        {
            if (vegetariano=="on")
            {
                vegeta = 1;
            }
            
            if (vegano=="on")
            {
                vegan = 1;
            }
            if (celiaco== "on")
            {
                celia = 1;
            }
            if (lacteos== "on")
            {
                lacte = 1;
            }
        }

        




    }
}

cocinitas/Cocinitas/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>

    <!-- BORRAR COSES!!

        - Unificar .css
        - Revisar si hi ha links duplicats (bootstraps...)

        -->
  
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - Cocinitas</title>

    <environment names="Development">

        <link rel="stylesheet" type="text/css" href="~/css/style_cocinitas.css" />

        <script src="https://code.jquery.com/jquery-3.2.1.min.js"
                integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
                crossorigin="anonymous"></script>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

        <script src="~/js/selectize.js"></script>

        <link rel="stylesheet" type="text/css" href="~/css/selectize.bootstrap3.css">

        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    </environment>

    <environment names="Staging,Production">

        <link rel="stylesheet" type="text/css" href="~/css/style_cocinitas.css" />

        <script src="https://code.jquery.com/jquery-3.2.1.min.js"
                integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
                crossorigin="anonymous"></script>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

        <script src="~/js/selectize.js"></script>

        <script src="starrr.min.js"></script>

        <link rel="stylesheet" type="text/css" href="~/css/selectize.bootstrap3.css">

        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
    
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" id="navbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="btn"><img src="http://i.imgur.com/c5HR38B.png" width="50px" height="50px"></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                        <li><a asp-area="" asp-controller="Home" asp-action="Presentacion">Presentación</a></li>
                    @*Comprueba si el usuario tiene nombre, no lo tiene muestra los botones login y registro, sino muestra el botón de usuario.*@         
                    @if (ViewData["usNombre"] == null)
                    {
                        <li><a asp-area="" asp-controller="usuarios" asp-action="login" id="notLogged"><button type="button" class="btn btn2 green">Accede</button></a></li>
                        <li><a asp-area="" asp-controller="usuarios" asp-action="registro" id="notLogged"><button type="button" class="btn btn2 red">Regístrate</button></a></li>
                    }
                    else
                    {
                       <li class="dropdown" @*style="display:none" *@ id="logged">
                            <a asp-area="" asp-controller="usuarios" asp-action="dropdown-usuario" data-toggle="dropdown"><button type="button" class="dropdown-toggle btn btn2 red">@ViewData["usNombre"]</button></a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                                <li><a href="#">Perfil</a></li>
                                <li><a href="#">Favoritos</a></li>
                                <li><a href="#">Historial</a></li>
                                <li><a asp-area="" asp-controller="recetas" asp-action="subereceta">Sube tus Recetas</a></li>
                                <li><a asp-area="" asp-controller="usuarios" asp-action="logout">Logout</a></li>
                            </ul>
                       </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Cocinitas</p>
        </footer>
    </div>

    <environment names="Development">

    </environment>

    <environment names="Staging,Production">

    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>